"""
End-to-end pipeline:
  1. Random-effects meta-analysis of operative vs nonoperative treatment (midshaft).
  2. Hierarchical Bayesian meta-analysis (PyMC/NUTS) across midshaft + distal.
  3. Interpretable predictive model for nonunion (points score + logistic + tree).
  4. Auto-generated report (report/REPORT.md) that stitches results and figures.

Run (inside the venv, since step 2 needs PyMC):  python run_all.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

import numpy as np
import pandas as pd
import meta_analysis
import risk_model
import hierarchical_meta

ROOT = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(ROOT, "outputs")
REPORT = os.path.join(ROOT, "report", "REPORT.md")


def fmt_table(df, floatfmt=3):
    return df.round(floatfmt).to_markdown(index=False)


def main():
    print("\n########## 1. META-ANALYSIS (midshaft) ##########\n")
    ma_results, ma_summary = meta_analysis.run()

    print("\n########## 2. HIERARCHICAL META-ANALYSIS (midshaft + distal) ##########\n")
    hm = hierarchical_meta.run()

    print("\n########## 3. PREDICTIVE MODEL ##########\n")
    rm = risk_model.run()

    print("\n########## 4. REPORT ##########\n")
    trials = pd.read_csv(os.path.join(ROOT, "data", "meta_analysis_trials.csv"))
    ma_txt = open(os.path.join(OUT, "meta_analysis_report.txt")).read()
    rr = ma_results["RR"][2]
    orr = ma_results["OR"][2]
    risk_op, risk_nonop, ard, nnt = meta_analysis.number_needed_to_treat(trials)
    tree_rules = open(os.path.join(OUT, "decision_tree_rules.txt")).read()

    # Hierarchical model summary values for the report.
    hs = hm["summary"].set_index("param")
    h_overall = hs.loc["Overall (both locations)"]
    h_mid = hs.loc["Midshaft"]
    h_dist = hs.loc["Distal (lateral-third)"]
    sub = hm["subgroups"]
    tau_med = float(np.median(hm["tau"]))
    tau_lo, tau_hi = np.percentile(hm["tau"], [2.5, 97.5])
    omega_med = float(np.median(hm["omega"]))
    omega_lo, omega_hi = np.percentile(hm["omega"], [2.5, 97.5])

    md = f"""# Clavicle fracture outcomes: meta-analysis and interpretable risk model

*Auto-generated by `run_all.py`. Figures are in `../outputs/`.*

This project answers three linked questions about **clavicle fractures**:

1. **Intervention effect (midshaft)** — does operative fixation reduce nonunion
   versus nonoperative care, and by how much? (random-effects meta-analysis)
2. **Does that hold for distal fractures too?** — a hierarchical Bayesian
   meta-analysis pooling across fracture location (midshaft + distal).
3. **Individual risk** — for a patient treated nonoperatively, what is their
   probability of nonunion given patient and fracture factors? (an interpretable
   predictive model)

Data provenance, references and an honesty note on the modelling are in
[`../data/REFERENCES.md`](../data/REFERENCES.md).

---

## Part 1 — Meta-analysis: operative vs nonoperative

Six randomized controlled trials ({int(trials['n_op'].sum()+trials['n_nonop'].sum())}
patients) compared plate/intramedullary fixation with sling immobilisation for
displaced midshaft clavicle fractures, reporting nonunion.

![Forest plot, risk ratio](../outputs/forest_rr.png)

**Headline result**

| Metric | Value |
|---|---|
| Crude nonunion, operative | {risk_op*100:.1f}% |
| Crude nonunion, nonoperative | {risk_nonop*100:.1f}% |
| Absolute risk reduction | {ard*100:.1f} percentage points |
| Number needed to treat (surgery to prevent 1 nonunion) | {nnt:.0f} |
| Pooled risk ratio (random effects) | **{rr.estimate:.2f}** (95% CI {rr.ci_low:.2f}–{rr.ci_high:.2f}) |
| Pooled odds ratio (random effects) | {orr.estimate:.2f} (95% CI {orr.ci_low:.2f}–{orr.ci_high:.2f}) |
| Heterogeneity | I² = {rr.I2:.0f}%, τ² = {rr.tau2:.3f}, Cochran Q p = {rr.p_Q:.2f} |

Operative fixation reduces the relative risk of nonunion by roughly
**{(1-rr.estimate)*100:.0f}%**. Heterogeneity is negligible (I² = {rr.I2:.0f}%),
so the trials tell a consistent story, and the pooled estimate matches the
published literature (RR ≈ 0.14). **But** the NNT of ~{nnt:.0f} means most
patients treated nonoperatively still unite; surgery carries its own harms
(hardware, infection, ~17% elective plate removal in Woltz). This is exactly
why an *individual* risk model is useful — to target surgery at the patients
most likely to fail nonoperative care.

The method is DerSimonian–Laird random effects on the log risk ratio with a 0.5
continuity correction for zero-event arms, implemented transparently in
[`src/meta_analysis.py`](../src/meta_analysis.py).

---

## Part 2 — Hierarchical meta-analysis: does it hold for distal fractures?

Distal (lateral-third / Neer type II) clavicle fractures behave differently
biomechanically and have a **much sparser evidence base** — essentially one RCT
(Hall 2021) plus observational comparative cohorts. Analysing them alone gives
wide, unstable estimates; ignoring location and lumping everything together
hides real differences. A **hierarchical (multilevel) model** is the right tool:
studies are nested within fracture location, and both levels have their own
variance, so the distal subgroup **borrows strength** from the overall effect
while still getting its own estimate.

**Model** (3-level, on the log risk ratio; fitted with PyMC / NUTS):

```
y_i      ~ Normal(theta_i, s_i^2)        # observed log-RR | study effect
theta_i  ~ Normal(mu_location, tau^2)     # study | fracture-location mean
mu_g     ~ Normal(M, omega^2)             # location mean | overall mean
M ~ Normal(0, 10);  tau, omega ~ HalfNormal(1)
```

Non-centred parameterisation, 4 chains. Convergence was clean
(**{int(hm['diverging'])} divergences, max R-hat = {hm['max_rhat']:.3f}**, ESS in
the thousands — see [`outputs/hier_diagnostics.csv`](../outputs/hier_diagnostics.csv)).

![Hierarchical forest plot](../outputs/hier_forest.png)

| Estimate | Pooled RR for nonunion (95% credible interval) |
|---|---|
| **Overall (both locations)** | **{h_overall['RR_median']:.2f}** ({h_overall['RR_lo']:.2f}–{h_overall['RR_hi']:.2f}) |
| Midshaft | {h_mid['RR_median']:.2f} ({h_mid['RR_lo']:.2f}–{h_mid['RR_hi']:.2f}) |
| Distal (lateral-third) | {h_dist['RR_median']:.2f} ({h_dist['RR_lo']:.2f}–{h_dist['RR_hi']:.2f}) |
| Between-study SD, τ | {tau_med:.2f} ({tau_lo:.2f}–{tau_hi:.2f}) |
| Between-location SD, ω | {omega_med:.2f} ({omega_lo:.2f}–{omega_hi:.2f}) — weakly identified (2 groups) |

**Findings**

- Operative fixation reduces nonunion in **both** locations; the location means
  are almost identical (posterior probability that midshaft RR < distal RR ≈
  {hm['p_mid_lower']:.2f} — i.e. no evidence of a location difference in the
  *relative* effect).
- **Partial pooling tightens the sparse distal estimate.** Fitting distal
  studies on their own (no cross-location pooling) gives RR
  {sub['distal'].estimate:.2f} ({sub['distal'].ci_low:.2f}–{sub['distal'].ci_high:.2f});
  the hierarchical model sharpens this to
  {h_dist['RR_median']:.2f} ({h_dist['RR_lo']:.2f}–{h_dist['RR_hi']:.2f}) by
  borrowing strength from the overall effect. The shrinkage of every study toward
  its group/overall mean is shown below.
- The **overall** credible interval ({h_overall['RR_lo']:.2f}–{h_overall['RR_hi']:.2f})
  is *wider* than either subgroup — correctly, because it propagates the
  between-location uncertainty (ω) rather than pretending the two locations are
  the same study population.

![Shrinkage](../outputs/hier_shrinkage.png)
![Variance components](../outputs/hier_variance.png)

**Clinical caveat that the relative effect hides:** distal fractures have a far
higher *baseline* nonoperative nonunion risk (≈ 30–40% vs ≈ 15% midshaft), so
the same relative risk ratio implies a **larger absolute benefit** from surgery
in distal fractures. The relative effect is portable across location; the
absolute stakes are not. Implemented in
[`src/hierarchical_meta.py`](../src/hierarchical_meta.py).

---

## Part 3 — Interpretable predictive model for nonunion

Target: probability of nonunion after **nonoperative** treatment. Predictors are
the factors with the strongest and most reproducible evidence
(see `REFERENCES.md`): **smoking, complete displacement, fracture shortening
> 2 cm, comminution, female sex, and age**.

The brief asked for models that are *interpretable but have high predictive
power*. We built three and compared them under 5-fold cross-validation:

{fmt_table(rm['metrics'], 3)}

The two interpretable options — full logistic regression and the paper-and-pencil
**points score** — have essentially identical discrimination, and both beat the
decision tree. **Interpretability costs almost nothing here**, so the
recommended deployable model is the logistic regression (for a precise number)
or its distilled points score (for bedside use). An AUC around 0.72 is in line
with published clavicle nonunion models.

### 2a. Logistic regression (fitted OR vs published OR)

{fmt_table(rm['coefs'][['term','OR_fitted','OR_ci_low','OR_ci_high','p_value','OR_published']], 3)}

The fitted odds ratios recover the published effect sizes, which validates the
pipeline (see the honesty note in `REFERENCES.md` — the cohort is synthesised
from these published ORs because patient-level data is not public).

### 2b. Points score (bedside calculator)

One point equals one decade of age; every other factor is scaled to that unit.
Add the points, then read risk off the lookup curve
([`outputs/score_risk_lookup.csv`](../outputs/score_risk_lookup.csv)).

{fmt_table(rm['points_tbl'][['factor','condition','points']], 3)}

### 2c. Discrimination and calibration

![ROC](../outputs/roc.png)
![Calibration](../outputs/calibration.png)

The logistic model is well calibrated across the full risk range.

### 2d. Worked examples

{fmt_table(rm['examples'], 1)}

A young, minimally displaced fracture has a single-digit nonunion risk (surgery
rarely justified), whereas an older female smoker with a comminuted, shortened,
completely displaced fracture is a coin-flip — the group in whom the meta-analytic
benefit of surgery is concentrated.

---

## How to reproduce

```bash
pip install -r requirements.txt
python run_all.py
```

All figures and tables are regenerated into `outputs/`, and this report is
rewritten from the results. To run the predictive pipeline on **real** data,
replace `build_cohort()` in `src/risk_model.py` with a loader for a CSV that has
columns: age, female, smoking, complete_displacement, comminution,
shortening_gt2cm, nonunion.

### Decision-tree rules (for reference)

```
{tree_rules}```
"""
    with open(REPORT, "w") as f:
        f.write(md)
    print(f"Wrote {REPORT}")


if __name__ == "__main__":
    main()
